#!/usr/bin/env python3

input_DNA = 'CCGCGCACTATCTGTAGCCTCTCGCTGTGCGCCGGCCCCTCCGCCTTGGCAGAGGACCGAGAATCTGGTATTCTCCATATGTGGTGTACTGTACATACATATTTATCGCTATATTTCATGTACCTAGTCCTGTGATACTCTCGTCCGAGGGATCTTCTCGTCAGATCAAATTCCGTAGCTTCCCGAGGCTAGGTATGTTCCGTCTTGCGCAAGTAGTGAGTGTCACGACTGGCGCAGCGTACCGGCGTGTTTCCGAGGATGCTATGTCAGGCCAAGGTCTGCCGCTATACCACATCGAATTCTGTGGGAGATGACGTAAATAAAATGGCGCGGGAGTGGGGGTCGACAGGCTAGCCAGCATTTAGCCTCAGCTGCATTTTGCCCATTAATATACTGGCAGCTCAGTATAGGGTTCCTTGAATTAGAGGCATAATTCGGGCTGAAACTTAATGAATGACGGTTCATGCCGTTATCAGTGGGAGTGCCGACAGGGGTTCAACGGCTTAAAAGGGTAGTGTACATCGCGGTACCGGGGAGTTGCCACCCGGCGGGTACGGCTACTGCGTTTCCTTTTGTTACTATTCGGCTTGGGCGCTTTCTTAAGTAGCGAAACAGCGAACGCGATGCGTCTATAATAGGGAAAATATACCCAATTTGATTGAGCCACAGGAACTTCGTGCACAACAATCGTATTTAGTTCACCTTCGGTGTCATCGAAGAAATGCCCTCAGGGTATATGTCTTTAACGTCCAGTCACTAACATGGACTATCATTAGGATTACGAAGCAATATCCTGGCTAGAAACTAATACAAGGAACTCTCGGTCGCATCGCTACTGGTTAGGTACGGG'
reversed_DNA = input_DNA[::-1]

reversed_DNA_list = list(reversed_DNA)
for i in range(0, len(reversed_DNA_list)):
    if reversed_DNA_list[i] == 'A':
        reversed_DNA_list[i] = 'T'
    elif reversed_DNA_list[i] == 'T':
        reversed_DNA_list[i] = 'A'
    elif reversed_DNA_list[i] == 'G':
        reversed_DNA_list[i] = 'C'
    elif reversed_DNA_list[i] == 'C':
        reversed_DNA_list[i] = 'G'

reverse_complement_DNA = ''

reverse_complement_DNA = reverse_complement_DNA.join(reversed_DNA_list)
print(reverse_complement_DNA)


